server:
  port: 8888
spring:  application:    name: configuration-server        
  cloud:    config:      server:        git:
          uri: https://github.com/ShivakrishnaDharmavaram/olx-config
          default-label: main
          username: ShivakrishnaDharmavaram
          password: mygithubpassword          clone-on-start: true    