server:
  port: 9080
  
spring:
   config:
      import: configserver:http://localhost:8888         
   application:
    name: advertise-service
   zipkin:
     base-url: http://localhost:9411/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /olx-advertise
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
      
resilience4j:
  circuitbreaker:
    instances:
      STATUS-FROM-MASTER-DATA-SERVICE:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 1
        minimumNumberOfCalls: 2
        permittedNumberOfCallsInHalfOpenState: 1
        waitDurationInOpenState: 5s
      TOKEN-VALIDATION-SERVICE:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 1
        minimumNumberOfCalls: 2
        permittedNumberOfCallsInHalfOpenState: 1
        waitDurationInOpenState: 5s  
        

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
